services:
  - type: web
    name: vehicle-price-estimator
    env: python
    pythonVersion: 3.10.13   # ðŸ”¥ THIS LINE IS MANDATORY
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
